config/routes.rb
Rails.application.routes.draw do

  get '/' => 'sessions#welcome'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/signup' =>  'customers#new'
  delete '/logout' => 'sessions#destroy'

  get '/auth/facebook/callback', to: 'sessions#create_with_fb'
  resources :appointments
  resources :customers do 
    resources :appointments, only: [:new, :index]
  end
  resources :barbers



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true


 
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :barber
  belongs_to :customer

  accepts_nested_attributes_for :barber


  validate :appointment_datetime_cannot_be_in_the_past
  scope :order_by_appointment_datetime, -> {order(:appointment_datetime)}

  def appointment_datetime_cannot_be_in_the_past
    if appointment_datetime.present? && appointment_datetime < Date.today
      errors.add(:appointment_datetime, "can't be in the past")
    end
  end

end

app/models/barber.rb
class Barber < ApplicationRecord
    has_many :appointments
    has_many :customers, through: :appointments

    validates :name, uniqueness: true, presence: true 
    validates :name, format: { with: /\A[a-zA-Z\s]*\z/, message: "only allows letters and spaces" }
    validates :name, length: { minimum: 2 }
    validates :name, length: { maximum: 20 }
end

app/models/customer.rb
class Customer < ApplicationRecord
    has_many :appointments
    has_many :payment_profiles
    has_many :barbers, through: :appointments
    accepts_nested_attributes_for :payment_profiles

    validates :username, uniqueness: true, presence: true 
    validates :username, length: { minimum: 2 }
    validates :username, length: { maximum: 30 }

    has_secure_password


    


end

app/models/payment_profile.rb
class PaymentProfile < ApplicationRecord
  belongs_to :customer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    private
        def current_customer
            @current_customer ||= Customer.find_by_id(session[:user_id])
        end

        def valid_customer
            @customer = Customer.find_by_id(session[:user_id]) if params[:id].to_i == session[:user_id]

        end


end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController

    def new
        @customer = Appointment.find_by_id(params[:customer_id])
        @appointment = Appointment.new
        @appointment.build_barber
    end

    def create
        binding.pry
        if current_customer && current_customer == session[:user_id]
            @appointment = current_customer.appointments.build(appointment_params)
            @appointment.customer_id = session[:user_id]
            if @appointment.save
                redirect_to appointment_path(@appointment)
            else
                #flash[:message] = "#{@appointment.errors.full_messages.to_sentence}."
                render :new
            end
        else
            redirect_to '/'
        end

    end

    def show
        @appointment = Appointment.find_by_id(params[:id])
        redirect_to '/' if !@appointment
    end

    def index
        if params[:customer_id].to_i == session[:user_id]     #if user is logged in

            @customer = Customer.find_by_id(params[:customer_id])
            @appointments = @customer.appointments.order_by_appointment_datetime
        elsif current_customer

            redirect_to customer_path(current_customer)
        else
            redirect_to '/' 
        end
    end



    private

    def appointment_params
        #binding.pry

        if params[:appointment][:barber_attributes][:name] == ""
            params.require(:appointment).permit(
                :appointment_datetime,
                :style,
                :barber_id,
                :customer_id)
        else

            params.require(:appointment).permit(
            :appointment_datetime,
            :style,
            :barber_id,
            :customer_id,
            barber_attributes: [ :name, :mustache ]
            )
        end

    end


end

app/controllers/barbers_controller.rb
class BarbersController < ApplicationController


    def show
        @barber = Barber.find_by_id(params[:id])
        redirect_to '/' if !@barber
    end

    def index
        @barbers = Barber.all 
    end
    
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

    def new
        @customer = Customer.new
        @customer.payment_profiles.build(cc_name: "")
        # @customer.payment_profiles.build(cc_name: "")
    end

    def create
        #binding.pry
        @customer = Customer.create(customer_params)
        if @customer.save
            session[:user_id] = @customer.id
            redirect_to customer_path(@customer)
        else
            render :new
        end
    end

    def show
        if params[:id].to_i == session[:user_id]     #if user is logged in

            @customer = Customer.find_by_id(params[:id])
            @customer_appointments = @customer.appointments.order_by_appointment_datetime
        elsif current_customer

            redirect_to customer_path(current_customer)
        else
            redirect_to '/' 
        end
    end

    def edit
        @customer = valid_customer if valid_customer

    end


    def update
        @customer = Customer.find(params[:id])
        @customer.update(customer_params)
        redirect_to customer_path(@customer)
    end

    def customer_params
        params.require(:customer).permit(
          :username,
          :password,
          payment_profiles_attributes: [ :cc_name, :cc_number ]
        )
    end

end

app/controllers/payement_profiles_controller.rb
class Payment_profilesController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


    def welcome

    end

    def new
   
    end

    def create
        #binding.pry
        @customer = Customer.find_by(username: params[:customer][:username])
        if @customer.try(:authenticate, params[:customer][:password])
            session[:user_id] = @customer.id
            redirect_to customer_path(@customer)
        else
            flash[:error] = "***Login error*** try again"
            redirect_to login_path
        end


    #     return redirect_to(controller: 'sessions',
    #                    action: 'new') if !params[:user_id] || params[:user_id].empty?
    # session[:user_id] = params[:user_id]
    # redirect_to '/'
    end



    def destroy
        session.delete(:user_id)
        redirect_to '/'
    end

    def create_with_fb
        customer = Customer.find_or_create_by(authID: auth['uid']) do |u|
            u.username = auth['info']['name']
            u.password = 'password'
        end
        customer.save
        session[:user_id] = customer.id
        redirect_to customer_path(customer)

    end


    private

  def auth
    request.env['omniauth.auth']
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/barbers_helper.rb
module BarbersHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/appointments/index.erb
<h1> <%=@customer.username%>'s appointments </h1>


<% @appointments.each do |app| %>
    <li><%= app.style %> cut with <%= link_to app.barber.name, barber_path(app.barber_id) %> at <%= app.appointment_datetime %></li>
  <% end %>
  </ul>

app/views/appointments/new.erb
<h1> Make a new appointment! </h1>


<%= form_for @appointment do |f|%>

    <% if @appointment.errors.any? %>
    <div id="error_explanation">
        <h2>There were some errors:</h2>
        <ul>
        <% @appointment.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
        </ul>
    </div>
    <% end %>





    <div>
    <%= f.label "Date and Time" %>
    <%= f.datetime_local_field :appointment_datetime %>
    </div>
    <br>

    <div>
    <%= f.label "What style do you want?" %>
    <%= f.text_field :style %>
    </div>
    <br>
    <p> Choose a barber ...</p>
    <div>
    <%= f.collection_select :barber_id, Barber.all, :id, :name, :prompt => "Our Barbers.." %>
    </div>

    <p> ..OR..Name your barber: </p>
    <div>
    <%= f.fields_for :barber, @appointment.barber do |b| %>
        <%= b.label "Barber Name" %>
        <%= b.text_field :name %>
        
        <%= b.label "Mustached?" %>
        <%= b.check_box :mustache %>
    <% end %>
    </div>

<br>

    <%= f.submit "Make Appointment" %>

<% end %>

app/views/appointments/show.erb
<h1> <%=@appointment.customer.username%>'s Appointment:  </h1>
<h1> scheduled for <%= @appointment.appointment_datetime.strftime("%B %e, %Y at %l:%M %p")%></h1>

<br>
<br>
<h3> Style:
<%= @appointment.style %>
</h3>

<h3> Barber:  <%= link_to @appointment.barber.name, barber_path(@appointment.barber_id) %>
</h3>

<br>
<br>
<div> For customer: 
<%= link_to @appointment.customer.username, customer_path(@appointment.customer_id) %>
</div>
<br>

app/views/barbers/index.erb
<h1> barbers </h1>
<ul>
<% @barbers.each do |barber| %>
  <li>Name: <%= link_to barber.name, barber_path(barber) %> Number of Appointments: <%= barber.appointments.count %></li>
<br>
<% end %>
</ul>

app/views/barbers/show.erb
<h1> barber:  </h1>
<h1> <%= @barber.name %></h1>

<br>
<br>

<h3> Appointments: </h3>
<br>

<ul>

<% @barber.appointments.each do |app| %>
  <li><%= app.style %> cut with <%= link_to app.customer.username, customer_path(app.customer_id) %> at <%= app.appointment_datetime %></li>
<% end %>
</ul>

<br>
<br>

<br>

app/views/customers/edit.erb
<h1> edit <%= @customer.username %>

<%= form_for @customer do |f|%>

    <% if @customer.errors.any? %>
    <div id="error_explanation">
        <h2>There were some errors:</h2>
        <ul>
        <% @customer.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
        </ul>
    </div>
    <% end %>


    <%= f.label "Username:" %>
    <%= f.text_field :username %>

    <%= f.label "Password:" %>
    <%= f.password_field :password %>

<br>
<br>
<br>

    <%= f.fields_for :payment_profiles do |inner_form| %>
        <%= inner_form.label "Credit Card Nickname" %>
        <%= inner_form.text_field :cc_name %><br/>
    
        <%= inner_form.label "Credit Card Number" %>
        <%= inner_form.text_field :cc_number %><br/>
    <% end %>

    <%= f.submit "Sign up!" %>

<% end %>

app/views/customers/new.erb
<h1> New customer! signup </h1>



<%= form_for @customer do |f|%>

    <% if @customer.errors.any? %>
    <div id="error_explanation">
        <h2>There were some errors:</h2>
        <ul>
        <% @customer.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
        </ul>
    </div>
    <% end %>


    <%= f.label "Username:" %>
    <%= f.text_field :username %>

    <%= f.label "Password:" %>
    <%= f.password_field :password %>

<br>
<br>
<br>

    <%= f.fields_for :payment_profiles do |inner_form| %>
        <%= inner_form.label "Credit Card Nickname" %>
        <%= inner_form.text_field :cc_name %><br/>
    
        <%= inner_form.label "Credit Card Number" %>
        <%= inner_form.text_field :cc_number %><br/>
    <% end %>

    <%= f.submit "Sign up!" %>

<% end %>

app/views/customers/show.erb
<h1> Customer:  </h1>
<h1> <%= @customer.username %></h1>

<br>
<br>

<h3> <%= @customer.username%>'s <%= link_to "Appointments", customer_appointments_path(@customer.id) %>: <%= @customer_appointments.count %></h3>
<br>


<h3> Payment Profiles: </h3>
<br>
<ul>

<% @customer.payment_profiles.each do |payment_profile| %>
  <li><%= payment_profile.cc_name %></li>
<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Barbershop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <div>
    <% if session[:user_id] %>
      <%=  link_to "Log Out", logout_path, method: :delete %> 
      .    .
      <%= link_to "Your Profile", customer_path(session[:user_id]) %>
       .   .
      <%= link_to "Make a new appointment", new_customer_appointment_path(session[:user_id]) %>
    <% else %>
    <%= link_to "Home", '/' %>
    <%= link_to "Sign in with Facebook", '/auth/facebook' %>
      <% end %>
  </div>

  <body>
    <%= yield %> 
  </body>
</html>